#game
archmage_user:
    resource: "@ArchmageUserBundle/Controller"
    type: annotation
    prefix: /

archmage_game:
    resource: "@ArchmageGameBundle/Controller"
    type: annotation
    prefix: /

archmage_payment:
    resource: "@ArchmagePaymentBundle/Controller"
    type: annotation
    prefix: /

#fos
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /game/account/password

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /game/account/profile

fos_user_profile_show:
    path: /game/account/profile

#payum
payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"