# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                username_parameter: _username
                password_parameter: _password
                csrf_parameter: _csrf_token
                post_only: true
                always_use_default_target_path: true
                default_target_path: /game/kingdom/summary
            logout:
                path:   /logout
                target: /login
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/game, role: ROLE_USER }