services:
    twig.extension.text:
         class: Twig_Extensions_Extension_Text
         tags:
             - { name: twig.extension }
    app.twig_extension:
        class: Archmage\GameBundle\Twig\TwigExtension
        public: false
        tags:
            - { name: twig.extension }