<?php

namespace Archmage\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConstructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstructionRepository extends EntityRepository
{
}
