<?php

namespace Archmage\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AttackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackRepository extends EntityRepository
{
}
