<?php

namespace Archmage\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Archmage\GameBundle\Entity\Player;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findAllValidAttackTargetsByPlayer(Player $player)
    {
        $qb = $this->_em->createQueryBuilder();

        //COUNTERS
        $counters = $qb->select('a.attacker')
            ->from('ArchmageGameBundle:Attack', 'a')
            ->where($qb->expr()->eq('a.defender', $player))
            ->getQuery()
            ->getResult();

        //BLACKLIST
        $blacklist = $qb->select('a.defender')
            ->from('ArchmageGameBundle:Attack', 'a')
            ->where($qb->expr()->eq('a.attacker', $player))
            ->getQuery()
            ->getResult();

        //TARGETS
        $targets = $qb->select('p')
            ->from('ArchmageGameBundle:Player', 'p')
            ->andWhere($qb->expr()->In('p.id', $counters))
            ->andWhere($qb->expr()->notIn('p.id', $blacklist))
            ->getQuery()
            ->getResult();

        return $targets;
    }
}
