<?php

namespace Archmage\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findAllSpellsResearchablesByPlayer(Player $player)
    {
        //buscar todos los targets que puedan ser atacados por este jugador (un mago no puede atacar dos veces a otro mago en 12h pero si puede realizar contraataques)
        $qb = $this->_em->createQueryBuilder();


        return $qb->getQuery()->getResult();
    }
}
