<?php

namespace Archmage\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Archmage\GameBundle\Entity\Player;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findAllValidAttackTargetsByPlayer(Player $player)
    {
        $qb = $this->_em->createQueryBuilder();
        $now = new \DateTime('-12 hour');
        $now = "'".$now->format('Y-m-d H:i:s')."'";

        //COUNTERS
        $counters = $this->_em->createQueryBuilder()
            ->select('identity(counter.attacker)')
            ->from('ArchmageGameBundle:Attack', 'counter')
            ->andWhere($qb->expr()->eq('counter.defender', $player->getId()))
            ->andWhere($qb->expr()->gte('counter.datetime', $now));

        //BLACKLIST
        $blacklist = $this->_em->createQueryBuilder()
            ->select('identity(blacklist.defender)')
            ->from('ArchmageGameBundle:Attack', 'blacklist')
            ->andWhere($qb->expr()->eq('blacklist.attacker', $player->getId()))
            ->andWhere($qb->expr()->gte('blacklist.datetime', $now));

        //TARGETS
        $targets = $this->_em->createQueryBuilder()
            ->select('player')
            ->from('ArchmageGameBundle:Player', 'player')
            ->andWhere($qb->expr()->In('player.id', $counters->getDQL()))
            ->orWhere($qb->expr()->notIn('player.id', $blacklist->getDQL()))
            ->getQuery()
            ->getResult();

        return $targets;
    }
}
