<?php

namespace Archmage\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Proxies\__CG__\Archmage\GameBundle\Entity\Faction;

/**
 * SpellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpellRepository extends EntityRepository
{
    public function findAllOrderedByFaction(Faction $faction)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select(
            'iis.totalVariableCost,
            iis.totalNumberOfCalls,
            iis.totalDuration'
        )
        ->from('AppBundle:IndividualInvoiceSummary', 'iis')
        ->where('iis.startDate = :startDate')
        ->andWhere('iis.endDate = :endDate')
        ->andWhere('iis.numberOrCode = :numberOrCode')
        ->setParameters(array(
            'startDate' => $startDate,
            'endDate' => $endDate,
            'numberOrCode' => $numberOrCode,
        ));
        return $qb->getQuery()->getResult();
    }
}
