<?php

namespace Archmage\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TroopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TroopRepository extends EntityRepository
{
}
